name = "personal-leveling"
compatibility_date = "2024-09-01"

# Cloudflare Pages will serve static assets from the project root.
# Functions live under `functions/` and use the bindings below.

[[d1_databases]]
binding = "DB"            # Access in functions via env.DB
database_name = "plv-db"  # Created with: npx wrangler d1 create plv-db
# Fill in after creating the database in Cloudflare Dashboard or via CLI
# Example: database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

[vars]
APP_ENV = "development"

