name: Deploy to Droplet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate required secrets
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
          DROPLET_APP_DIR: ${{ secrets.DROPLET_APP_DIR }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          missing=0
          for var in SSH_PRIVATE_KEY DROPLET_HOST DROPLET_USER DROPLET_APP_DIR; do
            if [ -z "${!var}" ]; then
              echo "::error::Missing required secret: $var"
              missing=1
            fi
          done
          if [ -z "${SSH_PASSPHRASE}" ]; then
            echo "::notice::SSH_PASSPHRASE not provided. If your key has a passphrase, add secret SSH_PASSPHRASE."
          fi
          if [ "$missing" -eq 1 ]; then
            echo "One or more required secrets are missing. Configure them in GitHub → Settings → Secrets and variables → Actions."
            exit 1
          fi

      - name: Deploy over SSH (supports passphrase)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -eu
            APP_DIR=${{ secrets.DROPLET_APP_DIR }}
            REPO_URL=${{ github.server_url }}/${{ github.repository }}.git
            # Sanity check
            if [ -z "$APP_DIR" ]; then
              echo "[ERROR] DROPLET_APP_DIR is empty"
              exit 1
            fi
            if [ ! -d "$APP_DIR/.git" ]; then
              mkdir -p "$APP_DIR"
              git clone "$REPO_URL" "$APP_DIR"
            fi
            cd "$APP_DIR"
            echo "[INFO] Docker versions on remote:"
            (docker --version && docker compose version) 2>&1 || true
            # Use sudo for docker if necessary (non-interactive)
            if ! docker info >/dev/null 2>&1; then
              echo "[INFO] docker requires sudo. Verifying passwordless sudo..."
              if sudo -n true 2>/dev/null; then
                echo "[INFO] Using sudo -n for docker"
                DOCKER="sudo -n docker"
              else
                echo "[ERROR] Passwordless sudo is not configured for this user. Configure NOPASSWD for docker or add user to docker group, then retry."
                exit 1
              fi
            else
              DOCKER="docker"
            fi
            git fetch --all --prune 2>&1
            git reset --hard origin/main 2>&1
            export DOCKER_BUILDKIT=1
            export COMPOSE_DOCKER_CLI_BUILD=1
            # Only web and postgres, using base compose (no caddy/prod)
            COMPOSE_FILES="-f docker-compose.yml"
            COMPOSE="$DOCKER compose $COMPOSE_FILES"
            # Build & start only required services
            echo "[INFO] Pulling images (postgres, web) if present..."
            $COMPOSE pull postgres web 2>&1 || true
            echo "[INFO] Building web image..."
            if ! $COMPOSE build --no-cache web; then
              echo "[ERROR] Build failed (service: web). Check the build output above."
              exit 1
            fi
            echo "[INFO] Starting services (postgres, web)..."
            if ! $COMPOSE up -d postgres web; then
              echo "[ERROR] Up failed. Recent service logs:"
              $COMPOSE logs --tail=200 web || true
              $COMPOSE logs --tail=200 postgres || true
              exit 1
            fi
            $COMPOSE ps 2>&1
            echo "[INFO] Deploy finished for services: postgres, web"
