name: Deploy to Droplet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate required secrets
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
          DROPLET_APP_DIR: ${{ secrets.DROPLET_APP_DIR }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          missing=0
          for var in SSH_PRIVATE_KEY DROPLET_HOST DROPLET_USER DROPLET_APP_DIR; do
            if [ -z "${!var}" ]; then
              echo "::error::Missing required secret: $var"
              missing=1
            fi
          done
          if [ -z "${SSH_PASSPHRASE}" ]; then
            echo "::notice::SSH_PASSPHRASE not provided. If your key has a passphrase, add secret SSH_PASSPHRASE."
          fi
          if [ "$missing" -eq 1 ]; then
            echo "One or more required secrets are missing. Configure them in GitHub → Settings → Secrets and variables → Actions."
            exit 1
          fi

      - name: Deploy over SSH (supports passphrase)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -euo pipefail
            APP_DIR=${{ secrets.DROPLET_APP_DIR }}
            REPO_URL=${{ github.server_url }}/${{ github.repository }}.git
            if [ ! -d "$APP_DIR/.git" ]; then
              mkdir -p "$APP_DIR"
              git clone "$REPO_URL" "$APP_DIR"
            fi
            cd "$APP_DIR"
            echo "[INFO] Docker versions on remote:"
            (docker --version && docker compose version) || true
            # Use sudo for docker if necessary
            if ! docker info >/dev/null 2>&1; then
              echo "[INFO] Using sudo for docker"
              DOCKER="sudo docker"
            else
              DOCKER="docker"
            fi
            git fetch --all
            git reset --hard origin/main
            export DOCKER_BUILDKIT=1
            export COMPOSE_DOCKER_CLI_BUILD=1
            # Only web and postgres, using base compose (no caddy/prod)
            COMPOSE_FILES="-f docker-compose.yml"
            COMPOSE="$DOCKER compose $COMPOSE_FILES"
            # Build & start only required services
            $COMPOSE pull postgres web || true
            if ! $COMPOSE build --no-cache web; then
              echo "[ERROR] Build failed (service: web). Showing last logs..."
              $DOCKER compose $COMPOSE_FILES logs --tail=200 web || true
              exit 1
            fi
            if ! $COMPOSE up -d postgres web; then
              echo "[ERROR] Up failed. Showing logs for web and postgres..."
              $DOCKER compose $COMPOSE_FILES logs --tail=200 web || true
              $DOCKER compose $COMPOSE_FILES logs --tail=200 postgres || true
              exit 1
            fi
            $COMPOSE ps
            echo "[INFO] Deploy finished for services: postgres, web"
